### PR TITLE
Fix string interpolation error on failure to lookup secret by access token

### PR DESCRIPTION
**Pull request by lmouelle**
This fixes a positional error with string interpolation here, causing IndexErrors. Introduced from previous refactoring in [this commit](https://github.com/bitwarden/sm-ansible/commit/601df6c1cb8ce26e47a62b419888796671c2cdda). Pretty simple fix, encountered this while deploying an ansible playbook. The stack trace is revealed when running ansible with -vvv and pretty clearly shows the issue (replacing PII with 'SECRET' here):

exception during Jinja2 execution: Traceback (most recent call last):
  File "/home/SECRET/.ansible/collections/ansible_collections/bitwarden/secrets/plugins/lookup/lookup.py", line 370, in get_secret_data
    secret: SecretResponse = client.secrets().get(secret_id)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/SECRET/.local/lib/python3.12/site-packages/bitwarden_sdk/bitwarden_client.py", line 41, in get
    result = self.client._run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/SECRET/.local/lib/python3.12/site-packages/bitwarden_sdk/bitwarden_client.py", line 32, in _run_command
    raise Exception(response["errorMessage"])
Exception: Received error message from server: [404 Not Found] {"message":"Resource not found.","validationErrors":null,"exceptionMessage":null,"exceptionStackTrace":null,"innerExceptionMessage":null,"object":"error"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ansible/template/__init__.py", line 873, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/SECRET/.ansible/collections/ansible_collections/bitwarden/secrets/plugins/lookup/lookup.py", line 288, in run
    return self.get_secret_data(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/SECRET/.ansible/collections/ansible_collections/bitwarden/secrets/plugins/lookup/lookup.py", line 374, in get_secret_data
    error_message = f"{SECRET_LOOKUP_ERROR.format(secret_id)}: {e}"
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Replacement index 1 out of range for positional args tuple
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '{'SECRET': {'SECRET': \"{{ lookup('bitwarden.secrets.lookup', 'SECRET') }}\"}}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'bitwarden.secrets.lookup'. Error was a <class 'IndexError'>, original message: Replacement index 1 out of range for positional args tuple. Replacement index 1 out of range for positional args tuple"
}

## 🎟️ Tracking

Created this drive by fix to help y'all out, not actually sure how you track this

## 🚧 Type of change

-   🐛 Bug fix

## 📔 Objective

So my error messages are far less confusing and not obfuscated by unrelated IndexErrors 

## 📋 Code changes

-   **lookup.py:** Bug is here

## ⏰ Reminders before review

-   Contributor guidelines followed
-   All formatters and local linters executed and passed
-   Written new unit and / or integration tests where applicable
-   Protected functional changes with optionality (feature flags)
-   Used internationalization (i18n) for all UI strings
-   CI builds passed
-   Communicated to DevOps any deployment requirements
-   Updated any necessary documentation or informed the documentation team

## 🦮 Reviewer guidelines

-   👍 (`:+1:`) or similar for great changes
-   📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
-   ❓ (`:question:`) for questions
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
    issue and could potentially benefit from discussion
-   🎨 (`:art:`) for suggestions / improvements
-   ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
-   🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
-   ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by jodanpotasu** [comment]
I just spent an hour looking to see where I went wrong copying step by step from the tutorial because of this bug :P

**Comment by coltonhurst** [comment]
Thanks @lmouelle for this PR!

I've created the internal ticket [SM-1224](https://bitwarden.atlassian.net/browse/SM-1224) to track this.

**Comment by lmouelle** [comment]
@coltonhurst quick poke, can I can someone to review/approve this? It's a trivial change for an obvious bug, I don't want this PR to rot and fall behind changes to main

**Comment by coltonhurst** [comment]
Hey @lmouelle no worries, we are planning on looking into this (and a related issue blocking this).

**Review by cd-bitwarden — CHANGES_REQUESTED** [review]
Hello, thank you so much for making this PR! I am reviewing the code, and there is a bug blocking me checking out your changes locally. I am waiting for a team member to fix requests in python as they are broken at the moment. However, from my first glance at this, it seems like the change might be equivalent. This leads me to believe that potentially once the python requests are fixed this issue will disappear without any changes. Please let me know your thoughts on this, as I am not a pro at python. 😄

**Review by cd-bitwarden — APPROVED** [review]
This looks good, thank you for fixing this!

**Comment by lmouelle** [comment]
hey @cd-bitwarden , I switched away from ansible so I had forgotten about this PR. I noticed this one I opened is still blocked because "PRs with the hold or needs-qa labels cannot be merged".

I don't know your workflow, it seems like this [corresponding PR](https://github.com/bitwarden/sm-ansible/pull/44) is blocked for the same reason? 
I don't see "hold" or "needs-qa" labels on either of these two PRs. Can you/someone take a very quick peek at this so we can merge it in? It should be very simple

**Comment by cd-bitwarden** [comment]
> hey @cd-bitwarden , I switched away from ansible so I had forgotten about this PR. I noticed this PR I opened is still blocked because "PRs with the hold or needs-qa labels cannot be merged".
> 
> I don't know your workflow, it seems like this [corresponding PR](https://github.com/bitwarden/sm-ansible/pull/44) is blocked for the same reason? I don't see "hold" or "needs-qa" labels on either of these two PRs. Can you/someone take a very quick peek at this so we can merge it in? It should be very simple
> 
> Or is something you do on your end, and reflect it back to github after? If so I can close this issue

Hello @lmouelle we have gone through all of the steps to get this ready for merging into a release soon, thank you so much for this contribution and for your patience with me during this process. 😄 QA has approved these changes and I will be merging this PR into main.

**Pull request merged**
